### ISSUE TITLE
Add process for paying "a chefe" 

### ISSUE THREAD

**Issue by rub1e** [dwyl/process-handbook#104]
_A patrão_ is being paid directly into her `PT` account via `transferwise`, so I just need to add a quick line about how to do that to the `finance handbook`

**Comment by iteles** [comment]
Haha Yea, thanks Portuguese bank loans forcing me to be paid in Euros whilst the £ is low 🙄 https://github.com/dwyl/phase-two

**Comment by rub1e** [comment]
Closing as #109 has been merged
