### ISSUE TITLE
New expenses process

### ISSUE THREAD

**Issue by rub1e** [dwyl/process-handbook#126]
Xero have cheekily discontinued the ability to submit expenses for free from their app (and not told anyone about it) - so the process needs to be updated.

The stopgap process is: email receipts to @rub1e, he'll put them on the system and make sure you're paid

(In practice, this means I have to submit all expenses under my name on Xero, but then make the bank transfer to the appropriate person)

* [ ] Transfer everything done under the old system (raising bills) into the new system (raising expenses)
* [ ] Update expenses process in `process-handbook`
* [ ] Review existing expenses _policy_ 
* [ ] Update policy based on https://github.com/dwyl/hq/issues/123 and knowledge of how we actually deal with expense claims

**Comment by iteles** [comment]
🙄

**Comment by rub1e** [comment]
Weird. Annoying. And cheeky.

The 💶 / 💵 ones still have to be created as bills rather than expenses, by the by.

**Comment by iteles** [comment]
I no longer have access to add expenses as bills via the Xero app - it tells me all expenses have to be added through the new expenses app which has to be paid for. SO cheeky 😕 

A few questions:
+ How do we go about adding receipts that are more than one page (e.g. two sided receipts)?
+ What do I put in the VAT option for receipts that don't show VAT separately? VAT exempt?  No VAT?
+ How do I mark VAT in the Portugal receipts for now? IVA or nothing in the VAT option and just the IVA label for now so they don't appear in the VAT reports mistakenly?
+ What would you like me to do with receipts for expenses that have already been reconciled in Xero? Keep them all in a box to one side?

Also, as an FYI: In 'classic' expenses, you had a preference for having all expenses as drafts and then submitting one expense claim. For the new one, I have saved a number of them as a draft but it looks like I'm forced to submit them one by one.

**Comment by rub1e** [comment]
Yeah Xero is going through a bit of a makeover at the moment, and the new Expenses process is a brand new product - judging by the various posts on the support forum, we're not the only ones with frustrations.

> I no longer have access to add expenses as bills via the Xero app

Do you mean "add expenses as _expenses_"? Because you should still be able to add _bills_ from the app. (Neither here nor there, really, but just FYI!)

> How do we go about adding receipts that are more than one page (e.g. two sided receipts)?

The app won't let you do this (there are a dozen people on the support forum who've asked for it, they're aware). The way you'd do this is manually open an expense item on desktop, attach the photos, and manually fill in the details.

> What do I put in the VAT option for receipts that don't show VAT separately? VAT exempt? No VAT?

Put `No VAT` - the categories of `Exempt` and `Zero-rated` are specific and only apply to certain categories. 

> How do I mark VAT in the Portugal receipts for now?

Sorry, my fault - I created a VAT category of IVA before I knew that Xero treats that as UK VAT; I've now deleted it.

The answer is: ALL Portuguese receipts should be marked `No VAT`, but have the **LABEL** of **IVA** applied (screenshot)

![screenshot 2018-12-11 at 11 52 45](https://user-images.githubusercontent.com/11595920/49798901-5e317f00-fd3b-11e8-8cc7-a1988af65118.png)

> What would you like me to do with receipts for expenses that have already been reconciled in Xero? 

Once they're screenshotted and in Xero we can live without the paper, but... can't hurt, can it? I've got all receipts which have passed through my hands in a box, so they're all there in case we get audited. (That said, I'd imagine the hypothetical auditor would be very happy that we've got everything saved on Xero!)

> it looks like I'm forced to submit them one by one

Yeah same. It's really annoying for reconciliations etc because they come up as individual transactions. Nothing to be done. Not only that, but you can't assign them to different people, it locks it as whoever submitted the receipt: which means all of your receipts are under my name. 

> You're going to write all this up, right?

In answer to the question you didn't ask, yes I shall.

**Comment by iteles** [comment]
@rub1e 
@edwardcodes Will be helping me out a little this afternoon and I think it would actually be great for him to do a first pass of the write-up for you to edit rather than the other way around 👍

**Comment by rub1e** [comment]
@iteles I've added a task to get everything transferred from the old system to the new system

(This is in response to your asking me to check for duplicate expenses that exist in `Draft Bills` and `Expenses` at the same time)

So I've already cross-referenced the draft bills against expenses and removed duplicates - what's left in `Draft Bills` are **four expenses which I just need you to confirm were actually paid**. Once you've confirmed, I'll transfer them into the expenses system, delete the old bills, and then you can be paid (and we'll be totally done with the old system)

**Comment by iteles** [comment]
Completed. This system has been in effect and working.
