### ISSUE TITLE
Why is this repo called "ateam-master-reference" ? Rename to process-handbook?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/process-handbook#23]
@iteles why is this repository called `ateam-master-reference`?
seems like a bit of a "_mouth full_" and does not really describe what it _does_... 🤔 
could we consider an _alternative_? 
e.g something someone will actually be _searching_ for?

**Comment by iteles** [comment]
It was actually a stop-gap that was never rectified! Definitely time to make a change :+1:

**Comment by nelsonic** [comment]
https://youtu.be/PivWY9wn5ps?t=2m47s

**Comment by Cleop** [comment]
@nelsonic - I was about to open the same issue when I came across this one!
@iteles 
How about learn-scrum-mastery /mastering or learn-agile-project-management ?

There may be other areas you wanted to cover in this repo and if so, please let me know what they are. We could always create another repo for those or change the new proposed name to cover them too.

**Comment by iteles** [comment]
@cleop Let's go with `process-handbook` for now, anything's better than what it is now 😆

**Comment by Cleop** [comment]
@iteles would you be able to give me the permissions in order to be able to change the name please? And then I'll get on it 😊

**Comment by iteles** [comment]
@cleop Done!

**Comment by Cleop** [comment]
Thanks @iteles. Closing as this is now complete. Some people who may have this repo locally should follow this advice to rename their repo locally so it pushes to the right place: https://help.github.com/articles/renaming-a-repository/
