### ISSUE TITLE
Add How long does scrum mastering take?

### ISSUE THREAD

**Issue by Cleop** [dwyl/process-handbook#30]
Depending on the size of the team scrum master work is likely to take 2-3 days per 10 day sprint.

This may consist of:
- 30mins - 1 hour a day (stand up, backlog grooming, lifting blockers, scheduling next meetings etc)
- 30 mins - 1 hour per sprint doing sprint demo and sprint planning prep
- 1/2 day per sprint in sprint demo/ retrospectives/ sprint planning

**Comment by iteles** [comment]
@Cleop The context you've provided here is probably enough, but let's remove that last line. I would prefer not to contribute to the culture of 'professional scrum masters' more than I already am 🙄 

The biggest issue with this being https://github.com/dwyl/hq/issues/350
