### ISSUE TITLE
Review of Finances Section

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/process-handbook#46]
Links to:
https://github.com/dwyl/process-handbook/issues/35
https://github.com/dwyl/process-handbook/issues/38

https://github.com/dwyl/process-handbook/blob/master/finances.md

@iteles this was pushed by me to master by mistake, please could you review this MD file? I'm now on a new branch

**Comment by iteles** [comment]
+ An introduction on what this `.md` file is, its aims and intended audience would be useful. A good format to follow is our why/what/how, e.g. https://github.com/dwyl/process-handbook/blob/master/ProjectScopingTips.md
+ Some screenshots throughout for clarity and interest wouldn't hurt
+ Bookkeeping https://github.com/dwyl/process-handbook/blob/master/finances.md#bookkeeping
  + What is book keeping?
  + We have coming up on 200 reconciliations outstanding in Xero - what do these mean, how are they done and whose responsibility are they?
+ Expenses https://github.com/dwyl/process-handbook/blob/master/finances.md#expenses
  + How are these captured?
+ Contractor invoicing https://github.com/dwyl/process-handbook/blob/master/finances.md#contractor-invoicing
  + Please note that this is a prototype which is in temporary use whilst time is under construction
+ Forecasting https://github.com/dwyl/process-handbook/blob/master/finances.md#forecasting
  + Mentions of possible tools we haven't investigated or endorsed yet should go in an issue and not in this document

**Comment by markwilliamfirth** [comment]
@iteles I have added screenshots as another issues (https://github.com/dwyl/process-handbook/issues/64)

And submitted a PR for the changes requested https://github.com/dwyl/process-handbook/pull/63

**Comment by iteles** [comment]
I've reviewed the PR and merged, please close the issue if you're satisfied it can be closed 👍
