### ISSUE TITLE
Milestone Build Order

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/process-handbook#59]
Why do we build from top to bottom? When new issues are added to a milestone they are automatically added to the top of the list, but this doesn't work with our build flow - why not build bottom to top?

**Comment by iteles** [comment]
In short: Human convention. It's more natural for humans to start at the top and keep going down.

By and large, all of sprint planning is done in one go and the scope shouldn't change throughout the sprint, so all of the moving around should happen at once.

My experience has been that moving things around during that sprint planning session whilst they're being discussed is a small price to pay for opening the sprint milestone and immediately seeing what needs to be worked on next at the top, without scrolling. I've also found it's one less thing for new clients to remember with github (all lists start at the top).

Happy to hear other people's thoughts on this though and if validated, trial it on a new small project 👍

**Comment by Cleop** [comment]
@iteles - I agree and I think that actually putting new issues at the top of a milestone can be useful as these are often things added at a later date ie. bugs. It makes sure that the new issues are not forgotten about and the whole team sees them and is a helpful reminder to the product owner that they need to order them. On the whole, the Developers will not work on them if they're at the top and haven't been prioritised and/or it's clear from the listing that it's just been created. It may however prompt the Developers to check in with the Scrum Master/ Product Owner to make sure they're all on the same page about the new issues.

Are you happy to close this issue @iteles or do you think there is further discussion to be had here?

**Comment by iteles** [comment]
Happy to close this @Cleop 👍 

I wonder if it might be useful to have an FAQ section somewhere where we link to specific closed issues that come up more than once? (not the case here)
