### ISSUE TITLE
Written Notes from Stand Ups in Issues

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/process-handbook#67]
Is there a reason we don't record notes from standups in issues to have a transparent log of the progress of a project?

**Comment by iteles** [comment]
Yes, see mistake number 2 in the list here: https://www.scrumalliance.org/community/articles/2014/july/7-mistakes-during-the-daily-stand-up-meeting

**Comment by markwilliamfirth** [comment]
@iteles I don't think that contradicts my point - that talks about interrupting team members by referring to a log - my point is around recording a transparent log so everyone can see it

Links to https://github.com/dwyl/hq/issues/140

**Comment by iteles** [comment]
So sorry, that was a poor reference, I meant mistake no. 1 (was typing on my phone late at night):
> That was clearly a waste. No one would see or read this summary email, except perhaps the ScrumMaster, since he was not able to recall all of the topics the team was working on.

> This practice raises a feeling within the team of being micro-managed (also see Mistake #2 below), with someone wanting to keep track of what everyone is saying. In facts, it demotivates the team.

A stand up provides a quick summary of what should already be in github:
+ What was worked on the day before and by whom, captured in assignments and labels as well as PRs
+ What will be worked on today - discussed and then actioned throughout the day, moved to the top of the milestone during to reflect any reprioritisation if required
+ Blockers - captured in the relevant issues along with what is being done to resolve them

I don't believe transparency is an issue here at all. What do you see as the use case?

**Comment by markwilliamfirth** [comment]
@iteles it's about the transparency issue in the sense that people are not able to easily review what happened in these standups

**Comment by iteles** [comment]
@markwilliamfirth The question in that case is who would be reviewing the updates from a standup?

**Comment by markwilliamfirth** [comment]
@iteles anyone who wanted to know, it's just another action to meet our values

**Comment by iteles** [comment]
@markwilliamfirth My point is, we also aim to reduce complexity and be efficient with our efforts - if no one is going to read it, then it seems like an unnecessary additional process for people to remember that could potentially create a level of formality that could be less positive. We would also have to ensure it's done right to avoid:

> This practice raises a feeling within the team of being micro-managed (also see Mistake #2 below), with someone wanting to keep track of what everyone is saying. In facts, it demotivates the team.

In the past, the only time we have recorded anything separately is if one team member has been unable to attend the stand up (particularly if that is someone who not full time on the project), so that there is a quick run down. However, this is more about efficiency as it's jotted down in an ephemeral fashion - the actual information is already contained transparently on github.

If you want to trial this for the next project you scrum master, please do, we can review it in the retrospective.

**Comment by markwilliamfirth** [comment]
Yeah I'm just not sure our current practice is in line with our values, the stand ups are quite black box

**Comment by iteles** [comment]
@markwilliamfirth They are anything _but_ a black box. They are a quick summary of information that is _already public_ or very occasionally, when something is not already captured in issues, is made public by adding to the issues during the stand up (this is sometimes the case for blockers or next steps proposed on a standup). Things like changes of priorities are also captured in issues.

If you're running a stand up where the information isn't already captured in the issues, then there's a failure in process that needs to be addressed in documenting the work as it's being done and changes of priorities/acceptance criteria as they're happening.

**Comment by markwilliamfirth** [comment]
The point I'm making is the update isn't captured or transparent

This is also useful if for example, you or myself or someone else are filling in as scrum on a project if someone is ill or on holiday etc

It just doesn't make sense that the updates aren't transparent when that's one of our core values

I have no idea on the updates of other projects and I'm a part of dwyl, information in other issues doesn't give a snapshot update on the progress of a project

**Comment by iteles** [comment]
I still disagree. All of the information is available to anyone who cares enough to look at the backlog - 100% transparently (and if it's not, then that's a failure of mine for not making the processes clear enough and of the SM for not helping the team to enforce them).

Writing updates that no one will ever read is soul-destroying, still something that deeply annoys me about my time in the corporate world and I won't ask people to do it without a compelling reason to do so - i.e. demonstrating that they are indeed useful, they _will_ be read by others, are not a waste of time and do not erode our team dynamics.

So like I said here: https://github.com/dwyl/process-handbook/issues/67#issuecomment-332763008
> If you want to trial this for the next project you scrum master, please do, we can review it in the retrospective.

**Comment by markwilliamfirth** [comment]
@iteles transparency isn't just about information being able to be found, it's also about accessibility and how easy to find that information is. It's currently not easy at all for me to understand a snapshot update of what is going on with OA, EMF, etc

**Comment by markwilliamfirth** [comment]
Also I would definitely read them

**Comment by iteles** [comment]
If you can't go into a project like EMF and understand what is happening in less than 3 minutes, then there's something fundamentally broken with the way we're doing things. 

Let's sit down together in a couple of weeks when I'm back in the UK and we can show each other how we would go about getting a snapshot of what's happening in a project. We can feed this info into our github guide as per this issue: https://github.com/dwyl/github-reference/issues/9

**Comment by markwilliamfirth** [comment]
@iteles I don't even know where the EMF repo is - where is this recorded?

**Comment by iteles** [comment]
@markwilliamfirth Must have missed this question. It's recorded in the spreadsheet you put together for keeping a record of our projects: https://docs.google.com/spreadsheets/d/14fFQDGqhmucMQfkshR_8zdeZuZlhn8Rf1mFyXhi4Yi8/edit#gid=0

**Comment by markwilliamfirth** [comment]
@iteles thanks! I think we should record these in hq somewhere so they're public

In terms of this issue I also understand that @nelsonic is also keen (issue here: https://github com/dwyl/hq/issues/397#issuecomment-336846920) on improving the transparency (linked: https://github.com/dwyl/values/issues/1) and historical record of these standups.

Perhaps written notes is a good stop-gap for recorded standups?

**Comment by iteles** [comment]
Anyone who feels there is value here is very welcome to give it a go and report back! 👌🏻

**Comment by markwilliamfirth** [comment]
@iteles to me it's obvious that this (currently) mostly applies to you, as you run the majority of all standups. Also as I understand, you are in charge of company values (we should confirm this here https://github.com/dwyl/hq/issues/324) so if anyone should be trialing this it makes most sense for it to be you as it a task mostly done by you and related to our values, which I thought you wanted to lead on

**Comment by iteles** [comment]
As I think is pretty clear from this thread, this is something I don't believe in because I have had extensive experience of it being a waste of time and no help to transparency.

I'm very very happy to be proved wrong, but I wouldn't do this justice in testing it because of my experience with this in the past.

I have opened https://github.com/dwyl/product-owner-guide/issues/8 . Closing this issue, ready to be opened if anyone else sees it as an issue 👍
