### ISSUE TITLE
Are there any exceptions around merging straight to master?

### ISSUE THREAD

**Issue by iteles** [dwyl/process-handbook#74]
This question recently came up: Are there any times where I can merge straight to `master`?

What if I'm the owner of the repo? What if I'm in a rush? What if my QA is unavailable?

**Answer:** Not that we have ever come across. This is why protecting master branch is now part of our minimum repo requirements? https://github.com/dwyl/contributing#minimum-requirements-for-a-new-repository

We should add this to the repo.

**Comment by markwilliamfirth** [comment]
@iteles there is an exception - usually initial commits aren't reviewed?

**Comment by iteles** [comment]
Well noted @markwilliamfirth 👍 

The initial commit is created by github at the same time as the repo with the default name and description given on its inception, so this is only relevant for everything after the initial repo creation.

**Comment by markwilliamfirth** [comment]
I think sometimes I've seen yourself or nelson write a readme and submit without review (the initial readme) - is this not proper practice then? If so should we roll out branch protection to all repos as a priority? I would like to note that in my personal opinion I think pushing to master is useful sometimes and can stop issues with minor edits building up in PRs, but obviously happy to do whatever is agreed policy for everyone

**Comment by SimonLab** [comment]
The first rule of DwYl club is: You do not merge to master. The second rule of DWYl club is: You DO NOT merge to master!

**Comment by markwilliamfirth** [comment]
@iteles 

for example:

https://github.com/dwyl/process-handbook/commit/e8d77194fd2ec2b6b95b667aaac53b3b36587b82

https://github.com/dwyl/process-handbook/commit/d2456888c567e1adee29132eee9729fcbf24dd7d

https://github.com/dwyl/process-handbook/commit/47fd34b64b36bd2e3ee3ce2e906851d32c87c451

https://github.com/dwyl/process-handbook/commit/92b595617b83b649de17c341c6f6ba830a86cd95

**Comment by nelsonic** [comment]
Don't confuse _creating_ a repository from scratch
where the person is doing _all_ the work up-front on the `master` branch (_pre-workflow_)
with making an _update_ to an _existing_ repository/project (_well-defined workflow_)

I didn't `make` any of these `memes` ... 
https://www.google.co.uk/search?tbm=isch&q=git+push+master+meme
![image](https://user-images.githubusercontent.com/194400/32239666-10da8f34-be63-11e7-928f-c00f552dd2c5.png)
![image](https://user-images.githubusercontent.com/194400/32239744-57300018-be63-11e7-8464-1389b9f8e0ee.png)
![image](https://user-images.githubusercontent.com/194400/32239878-ad220b4c-be63-11e7-82f0-49180949fb8e.png)
Pushing to `master` is _generally_ frowned upon in the community.
Orgs/teams that _allow_ `git push origin master` _generally_ have "workflow & communication issues". 
Perhaps we need to be more _clear_ in https://github.com/dwyl/contributing ...?

**Comment by markwilliamfirth** [comment]
Is there a way to mass protect all the master branches on all +200 repos at the same time without having go to the settings of each individual repo?

**Comment by iteles** [comment]
Not that I know of.

**Comment by nelsonic** [comment]
https://developer.github.com/v3/repos/branches/#update-branch-protection

**Comment by iteles** [comment]
We could write a script to iterate through...

**Comment by Cleop** [comment]
@iteles - has this now been done based upon the issue reference above being closed?

**Comment by iteles** [comment]
👍 https://github.com/dwyl/hq/issues/420
