### ISSUE TITLE
Write up summary of the Google Design sprint

### ISSUE THREAD

**Issue by iteles** [dwyl/process-handbook#80]
[x] MD file to be linked here once @iteles has reviewed

We often talk about Google Design sprints and next year we will have some projects that allow us to exercise this muscle. 
I would ideally like to include a little bullet point summary of this in our proposals.

Whereas this will eventually be backed up by videos, for now, some research and a summary of this process would be a fantastic starting point.

**Comment by rub1e** [comment]
The Google Design Sprint process is outlined here: https://github.com/dwyl/process-handbook/blob/master/google-design-sprint.md

**Comment by iteles** [comment]
Great job @rub1e, thank you! Feeling all kinds of happy that tasks are being zipped through so quickly ❤️
