### ISSUE TITLE
Should we keep using milestones?

### ISSUE THREAD

**Issue by iteles** [dwyl/process-handbook#92]
We are starting to use [Github projects](https://help.github.com/articles/about-project-boards/) across our projects and with that, a `Sprint backlog` column means we no longer strictly _need_ [milestones](https://github.com/dwyl/process-handbook#step-5---close-the-sprint-milestone-on-github) to keep track of issues in milestones.

Or do we?

Linked to #37.

**Comment by nelsonic** [comment]
@iteles the functionality of GH Projects & Milestones _overlaps_ somewhat.
but (IMO) the `main` advantage of Milestones is that the PO/team 
can see the percentage completion for the "sprint" (_milestone_)
and the sprint is "grouped" by a clear "theme" (_the title of the milestone_).

**Comment by iteles** [comment]
The grouping that the milestone has provided us has been essential as the issues themselves move from column to column.
