### ISSUE TITLE
Invoice Google Form "leaking" Personal Data

### ISSUE THREAD

**Issue by nelsonic** [dwyl/process-handbook#97]
The invoicing google form shows the names of people in a `<ul>`:
![image](https://user-images.githubusercontent.com/194400/39761226-7307ed5e-52cf-11e8-996c-3edf6973ec44.png)

While these names are on the website: https://dwyl.com/team
It's still not _desirable_ to have a `public` form with people's personal details visible ...

Saw this will trying to help @edwardcodes submit an invoice (_and his name is **not** on the list..._)

**Comment by iteles** [comment]
This was an incredibly buggy system that we no longer use. This information is no longer available to view.

It leaked personal data, sent duplicate invoices and failed to work on numerous occasions. It was incredibly buggy.
It also relied on a complete manual input _and checking process_ of hours/days worked which was a total fail.

Closing as thankfully no longer relevant.
